language: rust
install:
    - sudo apt-get install libXxf86vm-dev xdotool
    - git clone https://github.com/glfw/glfw.git
    - cd glfw
    - git checkout 3.0.3
    - cmake -DCMAKE_C_FLAGS=-fPIC -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF .
    - make
    - sudo make install
    - cd ..
script:
    - cargo build
    - cargo test
    - cd src/example
    - cargo build