[package]
name = "genmesh"
version = "0.5.0"
authors = [
    "Coraline Sherratt <cora.sherratt@gmail.com>",
    "Dzmitry Malyshau <kvarkus@gmail.com>",
]

license = "Apache-2.0"
description = "A package for generating 3D meshes"
homepage = "https://github.com/gfx-rs/genmesh"
repository = "https://github.com/gfx-rs/genmesh"

[lib]
name = "genmesh"
path = "src/lib.rs"

[dependencies]
cgmath = "0.14"
mint = "0.2"
